sudo: required

language: python

dist: xenial

repo_token: OPhHHVuNsV4pjnZmooPOauAzaQIHVumz0

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install pytest

script:
  - pytest

after-success:
  - coveralls
  
services:
  - postgresql

addons:
  postgresql: "9.6"

before-script:
  - echo "this is a test"
  - bash install-postgres-10.sh
  - psql -c "create database politico_test;" -U postgres
  - psql -c "CREATE USER weqe WITH PASSWORD '4ndel4';" -U postgres
  - psql -c "GRANT CONNECT ON DATABASE politico_test TO weqe;" -U postgres 


  
