language: python

dist: xenial

repo_token: OPhHHVuNsV4pjnZmooPOauAzaQIHVumz0

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install pytest

script: 
  - bash build.sh
  - py.test --cov=politicoapi politico_api/tests/

after-success:
  - coveralls


