language: python

dist: xenial

python:
  - "3.6"

before_install:
  - pip install coveralls
  - pip install pytest pytest-cov

install:
  - pip install -r requirements.txt

script: 
  - bash build.sh

after_success:
  - coveralls