language: python

dist: xenial

python:
  - "3.6"

install:
  - pip install python-coveralls
  - pip install coverage
  - pip install -r requirements.txt

script: 
  - bash build.sh

after_success:
  - coveralls